<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>testtools.testcase._ExpectedFailure : API documentation</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
    <link href="apidocs.css" type="text/css" rel="stylesheet" />
    
    
  </head>
  <body>
    <h1 class="class private">t.t._ExpectedFailure(<span title="Exception">Exception</span>) : class documentation</h1>
    <p>
      <span id="part">Part of <a href="testtools.html">testtools</a>.<a href="testtools.testcase.html">testcase</a></span>
      
      <a href="classIndex.html#testtools.testcase._ExpectedFailure">View In Hierarchy</a>
    </p>
    <div>
      
    </div>
    <div class="docstring">
      <div><p>An expected failure occured.</p>
<p>Note that this exception is private plumbing in testtools' testcase
module.</p><table class="fieldTable"></table></div>
    </div>

    
    <div id="splitTables">
      
      
    </div>
    
    

    
    <address>
      <a href="index.html">API Documentation</a> for <a href="https://github.com/testing-cabal/testtools">testtools</a>, generated by <a href="https://launchpad.net/pydoctor/">pydoctor</a> at 2015-05-10 23:16:58.
    </address>
  </body>
</html>